version: "3.8"

services:
  # Monero Daemon
  monerod:
    image: sethsimmons/simple-monerod:latest
    container_name: based-market-monerod
    restart: unless-stopped
    volumes:
      - monerod_data:/home/monero/.bitmonero
    ports:
      - "18080:18080"
      - "18081:18081"
    networks:
      - based-market-network
    command:
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18081
      - --public-node
      - --no-igd
      - --no-zmq
      - --enable-dns-blocklist
      - --prune-blockchain
    healthcheck:
      test: ["CMD", "/usr/local/bin/monerod", "--version"]
      interval: 30s
      timeout: 5s
      retries: 1

  # Monero Wallet RPC
  monero-wallet-rpc:
    image: moneromint/monero:latest
    container_name: based-market-wallet-rpc
    restart: unless-stopped
    depends_on:
      monerod:
        condition: service_healthy
    volumes:
      - wallet_data:/home/monero/wallet
    ports:
      - "18083:18083"
    environment:
      - WALLET_PASSWORD=${MONERO_WALLET_PASSWORD:-marketplace123}
    command: >
      sh -c '
      echo "Waiting for monerod to be ready..." &&
      sleep 45 &&
      if [ ! -f /home/monero/wallet/marketplace-wallet ]; then
        monero-wallet-cli --testnet --generate-new-wallet /home/monero/wallet/marketplace-wallet --password "$$WALLET_PASSWORD" --mnemonic-language English --command exit || echo "Wallet creation failed, continuing...";
      fi &&
      monero-wallet-rpc
        --testnet
        --rpc-bind-ip=0.0.0.0
        --rpc-bind-port=18083
        --wallet-file /home/monero/wallet/marketplace-wallet
        --password "$$WALLET_PASSWORD"
        --confirm-external-bind
        --disable-rpc-login
        --daemon-address monerod:18081
        --log-level=1
      '
    healthcheck:
      test: ["CMD", "curl", "-sf", "-H", "Content-Type: application/json",
             "-d", "{\"jsonrpc\":\"2.0\",\"id\":\"0\",\"method\":\"get_balance\"}",
             "http://localhost:18083/json_rpc"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    networks:
      - based-market-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: based-market-backend
    restart: unless-stopped
    depends_on:
      monerod:
        condition: service_healthy
      monero-wallet-rpc:
        condition: service_healthy
    volumes:
      - backend_data:/app/data
      - ./backend:/app/src
      - ./wallet:/home/monero/wallet/
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3001
      - STORAGE_MODE=activitypub
      - DATABASE_URL=file:/app/data/marketplace.db
      - ACTIVITYPUB_DOMAIN=${ACTIVITYPUB_DOMAIN:-localhost:3001}
      - ACTIVITYPUB_BASE_URL=${ACTIVITYPUB_BASE_URL:-http://localhost:3001}
      - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret-change-in-production}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - MONERO_DAEMON_URL=http://monerod:18081
      - MONERO_WALLET_RPC_URL=http://monero-wallet-rpc:18083
      - MONERO_WALLET_PASSWORD=${MONERO_WALLET_PASSWORD:-marketplace123}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - CREATE_SAMPLE_DATA=${CREATE_SAMPLE_DATA:-false}
    networks:
      - based-market-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: based-market-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001/api}
      - VITE_ACTIVITYPUB_DOMAIN=${ACTIVITYPUB_DOMAIN:-localhost:3001}
    volumes:
      - ./frontend:/app/src
    networks:
      - based-market-network

  sqlite-web:
    image: coleifer/sqlite-web
    container_name: based-market-sqlite-admin
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:8080"
    volumes:
      - backend_data:/data
    command: sqlite_web -H 0.0.0.0 -x /data/marketplace.db
    networks:
      - based-market-network
    profiles:
      - development

networks:
  based-market-network:
    driver: bridge

volumes:
  monerod_data:
  wallet_data:
  backend_data:
